### ISSUE TITLE
Web demo URL not working

### ISSUE THREAD

**Issue by BrainCrumbz** [eduardoleao052/js-pytorch#24]
### Describe the Bug

Hi, just trying to open the web demo referenced in readme. But the URL [https://eduardoleao052.github.io/js-torch/assets/demo/demo.html](https://eduardoleao052.github.io/js-torch/assets/demo/demo.html) shows a "404 file not found" page.

Could you please share the URL? Thanks!

### Issue Checkbox

- [X] I added a descriptive title to this issue.
- [X] I searched the other issues on js-torch, and didn't find any reporting this same bug.
- [X] The bug is not resolved by updating to the latest version of js-pytorch on npm.

### Would you like to work on this issue?

None

**Comment by eduardoleao052** [comment]
Thank you so much for pointing it out! Fixed it!

**Comment by eduardoleao052** [comment]
The URL had an old name for the repo. The one on your post still won't open, but the one on the `README` now works, thanks again!

**Comment by eduardoleao052** [comment]
[Here](https://eduardoleao052.github.io/js-pytorch/assets/demo/demo.html) it is!
