### ISSUE TITLE
torch.load ?

### ISSUE THREAD

**Issue by GXcells** [eduardoleao052/js-pytorch#25]
### Describe the Feature

Would it be possible to add the torch.load function to read .pt files?

### Would you like to work on this issue?

None

**Comment by eduardoleao052** [comment]
I have implemented torch.load() and torch.save() functions using the `fs` library! An example is now in the README.md, under `Save and Load Models` Let me know if that's what you wanted.

**Comment by GXcells** [comment]
Thanks a lot. I am having hard time to make js-pytorch work using cdnjs so I cannot test it (I only work with cdnjs in my project). It seems I cannot correctly import torch

**Comment by eduardoleao052** [comment]
cdnjs support has been added recently. Took a little while but it's up and running!
