### ISSUE TITLE
Misleading name?

### ISSUE THREAD

**Issue by Kreijstal** [eduardoleao052/js-pytorch#30]
This says JS-PyTorch but it's actually written in TypeScript, so it should be TS-PyTorch no?

**Comment by eduardoleao052** [comment]
Hello! Thank you for the issue. The library is written in TypeScript, but that's mostly to keep the source-code organized and type-checked. Once deployed and published (compiled) the code is turned into simple JavaScript. So when you download the code from `npm`, the distribution files are in JavaScript and you can write JavaScript code normally.

Once again thanks for the issue!
