### ISSUE TITLE
Typo in the example for torch.randint

### ISSUE THREAD

**Issue by Bilsyp** [eduardoleao052/js-pytorch#31]
### Describe the Bug

I found a typo in the documentation for **torch.randint**, as well as in the example provided.

- **Location**: [tensor page -  torch.randint](https://eduardoleao052.github.io/js-pytorch/site/tensor/#torchrandint)

**Issue**: 

- The function signature has an incorrect description: "torch.rand(low, high, *shape, requires_grad=false, device='cpu') → Tensor" should be corrected.
    
- **The example also contains errors**:
```javascript
let a = torch.rand([3,2], false, 'gpu');
console.log(a.data); 
```

It should be like this right : 
```javascript
let a = torch.randint(1,7,[3,2] ,false, 'gpu');
console.log(a.data); 
```

### Screenshot or Screen Recording (optional)

![Screenshot 2024-08-25 144411](https://github.com/user-attachments/assets/d933c4e5-758e-4f59-87a6-40b06fb89985)

### Issue Checkbox

- [X] I added a descriptive title to this issue.
- [X] I searched the other issues on js-torch, and didn't find any reporting this same bug.
- [X] The bug is not resolved by updating to the latest version of js-pytorch on npm.

### Would you like to work on this issue?

None

**Comment by eduardoleao052** [comment]
Thanks for pointing it out! Fixed it in the docs
