### ISSUE TITLE
CDN for js-pytorch

### ISSUE THREAD

**Issue by rikyperdana** [eduardoleao052/js-pytorch#32]
### Describe the Feature

A CDN for js-pytorch like jsdeliver, unpkg, or cdnjs

### Motivation [optional]

It's way easier to import (or require) the entire bundled js-torch library this way. So I don't have to tell my students to go through the hassle of installing the error prone npm package system. I imagine the simplicity of adding a line of html script and voila, all the power of torch in a humble browser.

### Sample Code

`<script type="module">
    import { pipeline } from 'https://cdn.jsdelivr.net/npm/@xenova/transformers@2.17.2';
</script>`

### Would you like to work on this issue?

Yes

**Comment by eduardoleao052** [comment]
Added! 
The script tag is:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/js-pytorch/0.7.2/js-pytorch-browser.js" integrity="sha512-l22t7GnqXvHBMCBvPUBdFO2TEYxnb1ziCGcDQcpTB2un16IPA4FE5SIZ8bUR+RwoDZGikQkWisO+fhnakXt9rg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

Thanks for pointing it out!
