### ISSUE TITLE
Cannot import with Deno

### ISSUE THREAD

**Issue by wrnrlr** [eduardoleao052/js-pytorch#34]
### Describe the Bug

I wanted to try pytorch with Deno JS but I am running into some problems importing the NPM package.

```
> import * as pytorch from 'npm:pytorchjs'
Initialize ⣯ [00:02]
 - pytorchjs@0.1.5


Warning npmlog@4.1.2 is deprecated: This package is no longer supported.
Warning npmlog@1.2.1 is deprecated: This package is no longer supported.
Warning are-we-there-yet@1.1.7 is deprecated: This package is no longer supported.
Warning gauge@2.7.4 is deprecated: This package is no longer supported.
Warning are-we-there-yet@1.0.6 is deprecated: This package is no longer supported.
Warning fstream@1.0.12 is deprecated: This package is no longer supported.
Initialize ⣟ [00:02] 216/220cated: This package is no longer supported.
 - lcid@1.0.0
 - is-fullwidth-code-point@1.0.0: Glob versions prior to v9 are no longer supported
 - string_decoder@1.3.0.0 is deprecated:
Uncaught Error: Could not locate the bindings file. Tried:
 → /Users/me/Code/node_modules/.deno/@arition+torch-js@0.14.0/node_modules/@arition/torch-js/build/torch-js.node
```

### Issue Checkbox

- [X] I added a descriptive title to this issue.
- [X] I searched the other issues on js-torch, and didn't find any reporting this same bug.
- [X] The bug is not resolved by updating to the latest version of js-pytorch on npm.

### Would you like to work on this issue?

Yes

**Comment by eduardoleao052** [comment]
I'm not familiar with Deno, but if you are importing from npm, the package name should be "js-pytorch".
Does that solve the problem? If not, i'll look into it!

**Comment by wrnrlr** [comment]
sorry yes, I've got confused with another package.
