### ISSUE TITLE
Saving gpu network error

### ISSUE THREAD

**Issue by Seyronh** [eduardoleao052/js-pytorch#36]
### Describe the Bug

when saving and loading a cpu network goes fine but when i try to save a gpu network it says this
    const argumentTypes = new Array(kernelArguments.length);
    TypeError: Cannot read properties of null (reading 'length')

### Minimal Reproducible Code

class MSELoss extends torch.nn.Module {
	constructor() {
		super();
	}
	forward(z, y) {
		return z.sub(y).pow(2).sum().mean();
	}
} //Custom loss function
class NeuralNetwork extends torch.nn.Module {
	constructor() {
		super();
		this.w1 = new torch.nn.Linear(1, 256, "gpu");
		this.a1 = new torch.nn.ReLU();
		this.w2 = new torch.nn.Linear(256, 256, "gpu");
		this.a2 = new torch.nn.ReLU();
		this.w3 = new torch.nn.Linear(256, 4, "gpu");
	}
	forward(x) {
		let salida = this.w1.forward(x);
		salida = this.a1.forward(salida);
		salida = this.w2.forward(salida);
		salida = this.a2.forward(salida);
		salida = this.w3.forward(salida);
		return salida;
	}
}
let model = new NeuralNetwork();
let x = torch.randn([30, 1], undefined, "gpu");
let y = torch.randn([30, 4], undefined, "gpu");
let loss;
let loss_func = new MSELoss();
let optimizer = new torch.optim.Adam(model.parameters(), 3e-3);
for (let i = 0; i < 256; i++) {
	let z = model.forward(x);

	// Get loss:
	loss = loss_func.forward(z, y);

	// Backpropagate the loss using torch.tensor's backward() method:
	loss.backward();

	// Update the weights:
	optimizer.step();

	// Reset the gradients to zero after each training step:
	optimizer.zero_grad();

	// Print current loss:
	console.log(`Iter: ${i} - Loss: ${loss.data}`);
}
torch.save(model, "modeltarget.json");
model = torch.load(new NeuralNetwork(), "modeltarget.json");

### Screenshot or Screen Recording (optional)

Full error:
![imagen](https://github.com/user-attachments/assets/6f90d7f8-37e9-4cc7-8976-930bebaa0b4c)

### Issue Checkbox

- [X] I added a descriptive title to this issue.
- [X] I searched the other issues on js-torch, and didn't find any reporting this same bug.
- [X] The bug is not resolved by updating to the latest version of js-pytorch on npm.

### Would you like to work on this issue?

None

**Comment by eduardoleao052** [comment]
Hey! Great catch. I added a filter to remove kernels when saving, and it should be working now. Please let me know!
I ran your test here and it seems to be going well:

```javascript

const { torch } = require("js-pytorch");

class MSELoss extends torch.nn.Module {
    constructor() {
        super();
    }
    forward(z, y) {
        return z.sub(y).pow(2).sum().mean();
    }
} //Custom loss function
class NeuralNetwork extends torch.nn.Module {
    constructor() {
        super();
        this.w1 = new torch.nn.Linear(1, 64, "gpu");
        this.a1 = new torch.nn.ReLU();
        this.w2 = new torch.nn.Linear(64, 64, "gpu");
        this.a2 = new torch.nn.ReLU();
        this.w3 = new torch.nn.Linear(64, 4, "gpu");
    }
    forward(x) {
        let salida = this.w1.forward(x);
        salida = this.a1.forward(salida);
        salida = this.w2.forward(salida);
        salida = this.a2.forward(salida);
        salida = this.w3.forward(salida);
        return salida;
    }
}
let model = new NeuralNetwork();
let x = torch.randn([30, 1], undefined, "gpu");
let y = torch.randn([30, 4], undefined, "gpu");
let loss;
let loss_func = new MSELoss();
let optimizer = new torch.optim.Adam(model.parameters(), 3e-3);
for (let i = 0; i < 100; i++) {
    let z = model.forward(x);
    
    // Get loss:
    loss = loss_func.forward(z, y);
    
    // Backpropagate the loss using torch.tensor's backward() method:
    loss.backward();
    
    // Update the weights:
    optimizer.step();
    
    // Reset the gradients to zero after each training step:
    optimizer.zero_grad();
    
    // Print current loss:
    console.log(`Iter: ${i} - Loss: ${loss.data}`);
}
torch.save(model, "modeltarget.json");
model = torch.load(new NeuralNetwork(), "modeltarget.json");
let newOptimizer = new torch.optim.Adam(model.parameters(), 3e-3);

for (let i = 0; i < 100; i++) {
    let z = model.forward(x);
    
    // Get loss:
    loss = loss_func.forward(z, y);
    
    // Backpropagate the loss using torch.tensor's backward() method:
    loss.backward();
    
    // Update the weights:
    newOptimizer.step();
    
    // Reset the gradients to zero after each training step:
    newOptimizer.zero_grad();
    
    // Print current loss:
    console.log(`Iter: ${i} - Loss: ${loss.data}`);
}

```
